"use client";

import Head from "next/head";

import { useRouter } from "next/router";

import BookRender from "@/components/BookRender";

import ChapterForm from "~/components/ChapterForm";
export default function AddChapterPage() {
  const router = useRouter();
  const { bookid } = router.query; // `bookid` matches the dynamic segment name
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex w-full flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="flex w-full flex-col items-center gap-2"></div>
        </div>
        <div className="flex w-full">
          <div className="w-1/2">
            <ChapterForm bookId={bookid as string} />
          </div>
          <div className="w-1/2">
            <BookRender bookid={bookid as string} />
          </div>
        </div>
      </main>
    </>
  );
}
