"use client";
import Head from "next/head";
import { useRouter } from "next/router";
import BookRenderer from "~/components/BookRenderer";

import SectionForm from "~/components/SectionForm";
export default function AddSectionPage() {
  const router = useRouter();
  const bookId = router.query.bookid as string; // Moved and type-checked
  const chapterId = router.query.chapterid as string; // Moved and type-checked

  if (!bookId || !chapterId) return <p>No book or chapter found!</p>; // Added check for both bookId and chapterId

  return (
    <>
      <Head>
        <title>Add Section</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex w-full flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="flex w-full flex-col items-center gap-2"></div>
        </div>
        <div className="flex w-full">
          <div className="w-1/2">
            <SectionForm bookId={bookId} chapterId={chapterId} />
          </div>
          <div className="w-1/2">
            <BookRenderer />
          </div>
        </div>
      </main>
    </>
  );
}
